name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main   # or master, depending on your repo default branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/"             # Root folder (your index.html is here)
          api_location: ""              # No API (since frontend only)
          output_location: "/"          # No build step, deploy files as-is
          skip_app_build: true          # Don’t try npm/yarn build
